name: AWS Stack Update
on:
  push:
    branches:
    - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: update cfn stack
      uses: actions/aws/cli@master
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      with:
        args: cloudformation deploy --stack-name gitops --region us-west-2 --capabilities CAPABILITY_IAM --template-file infra.yml --notification-arns "arn:aws:sns:us-west-2:484951121041:deployment" --no-fail-on-empty-changeset
